VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFiles"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Property Get files() As Collection:: End Property

Property Let files(ByVal colNewFiles As Collection):: End Property

Property Let Add(ByVal file As IFile):: End Property
