VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IObjects"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Property Get Members() As Collection:: End Property

Property Let Members(ByVal colNewMembers As Collection):: End Property

Property Let Add(ByVal obj As IObject):: End Property
